apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: merry-backend
  name: merry-backend
spec:
  replicas: 3
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: merry-backend
    spec:
      containers:
      - image: abejide001/merry-backend
        name: merry-backend
        env:
         - name: NODE_ENV
           value: production
         - name: DB_PROD
           valueFrom:
            configMapRef:
              name: merry-postgres-credentials
              key: db_host_ip
        command: ["/bin/sh"]
        args: ["-c", "npm run build; npm run db:unmigrate; npm run db:migrate; npm run db:seed; npm run start"]
        ports:
        - containerPort: 9000
        resources: {}
      restartPolicy: Always
status: {}