apiVersion: v1
kind: PersistentVolume
metadata:
  name: merry-postgres-pv
  labels:
    name: merry-postgres-pv
spec:
  capacity:
    storage: 1Gi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: merry-pg-data-disk
    fsType: ext4